language: node_js
install: true
node_js:
  - "stable"
cache:
  directories:
  - node_modules
jobs:
  include:
    - stage: test
      script: bash onlyPostsChanged.sh
    - stage: build
      script: npm ci && npm run build
stages:
  - name: test
    if: type = pull_request AND head_branch = /^posts-.+/
  - name: build
    if: branch = master
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  keep_history: true
  on:
    branch: master
