language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
jobs:
  include:
    - stage: test
      script: bash onlyPostsChanged.sh
    - stage: install
      script: npm i
    - stage: build
      script: npm run build
    - stage: deploy
      script: echo "Deploying to GitHub pages ..."
    - script: mkdir -p public
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: public
        keep_history: true
stages:
  - name: test
    if: branch NOT IN (master, develop) AND head_branch NOT IN (master, develop)
  - name: install
    if: branch = master
  - name: build
    if: branch = master
  - name: deploy
    if: branch = master
