language: node_js
install: true
node_js:
  - "stable"
cache:
  directories:
  - node_modules
jobs:
  include:
    - stage: test
      script: bash onlyPostsChanged.sh
    - stage: build
      script: npm ci && npm run build
    - stage: deploy
      script: mkdir -p public
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: public
        keep_history: true
stages:
  - name: test
    if: branch NOT IN (master, develop) AND head_branch NOT IN (master, develop)
  - name: build
    if: branch = master
  - name: deploy
    if: branch = master
